import type {Metadata} from "next";
import {Mulish} from "next/font/google";
import{headers} from "next/headers"
import "./globals.css";
import React from "react";
import Navbar from "../components/layout/Navbar";
import {ThemeProvider} from "@/app/theme-provider";
import Footer from "@/components/layout/Footer";
import { cookieToInitialState } from 'wagmi'
import { config } from '@/config/config'
import Web3ModalProvider from '@/context/context'

const font = Mulish({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode }>) {
    const initialState = cookieToInitialState(config, headers().get('cookie'))
    return (
        
        <html lang="en" className="dark">
        <body className={font.className}>
       
        <ThemeProvider>
        <Web3ModalProvider initialState={initialState}>
            <Navbar/>
            {children}
            <Footer/>
            </Web3ModalProvider>
        </ThemeProvider>
        
        </body>
        </html>
    );
}
